import type { ReceiptFormRow } from "./documentExtraction";
import type { OcrLine, OcrToken } from "./ocrLayout";
import { groupTokensIntoLines, linesToText, valueRightOfLabel } from "./ocrLayout";
import { parseAmountKes } from "./ntsaExtraction";
import {
  applyBillRefOcrCorrections,
  digDeeperApplicationNo,
  digDeeperBillReferenceNo,
  digDeeperReceiptDate,
  digDeeperReceiptIdNumber,
  extractRawReceiptFields,
  parseHeaderValueRowFields,
  parseLongDateMatch,
  finalizeReceiptFormRow,
  isValidReceiptApplicationNo,
  isValidReceiptBillRef,
  isValidReceiptDate,
  isValidReceiptIdNumber,
  isValidReceiptName,
  isValidReceiptTotalKes,
  mergeReceiptFormRows,
  normalizeApplicationNo,
  parseReceiptOcrText,
  refineReceiptName,
  verifyMissingReceiptFields,
  type BillRefContext,
  type ParseReceiptOcrOptions,
} from "./ntsaReceiptExtraction";

export type ExtractionMethod =
  | "primary_keyword"
  | "secondary_keyword"
  | "layout_proximity"
  | "contextual"
  | "global_regex"
  | "synthetic_fallback"
  | "none";

export type FieldExtraction = {
  value: string | null;
  confidence: number;
  method: ExtractionMethod;
  /** True when value was auto-generated (not read from the document). */
  autoGenerated?: boolean;
};

export type ReceiptStructuredOutput = {
  Name: FieldExtraction;
  Date: FieldExtraction;
  ID_No: FieldExtraction;
  Application_No: FieldExtraction;
  Bill_Reference: FieldExtraction;
  Amount: FieldExtraction;
  Currency: FieldExtraction;
  overallConfidence: number;
  needsReview: boolean;
};

export const RECEIPT_EXTRACTION_RULES = `NTSA Payment Receipt extraction — target 99% field completion with tiered fallback.

OUTPUT JSON keys: Name, Date, ID_No, Application_No, Bill_Reference_No, Amount, Currency (KES).

FIELD PATTERNS:
- Name: after "Name:" — 3 capitalized words (NTSA receipts), [A-Z]+(?:\\s[A-Z]+){2,}
- Date: DD Month YYYY (year ≤ 2026), near top-right / DATE: label
- ID_No: exactly 9 digits after "ID No:" (not "ID Number")
- Application_No: PDL-[A-Z0-9]{9} after APPLICATION NO:
- Bill_Reference_No: 6–8 alphanumeric (often 7, e.g. MM4R4Q3), center header between app no and date
- Amount: Total KES — only 550 or 650 on NTSA receipts

TIERS (re-run lower tiers when confidence < 0.9):
1. Primary keyword + layout (0.95–1.0): APPLICATION NO:, BILL REFERENCE NO:, DATE:, ID No:, Name:, Total KES
2. Secondary region OCR (0.70–0.90): header value row, bill-ref column, mild-contrast header pass, customer block
3. Contextual proximity (0.50–0.70): bill ref between PDL- code and date; ID/name below RECEIPT PAID; split PDL reassembly
4. Global regex (0.35–0.55): pattern scan without labels; header value row triple parser
5. Synthetic fallback (0.10–0.30, autoGenerated=true): format-valid placeholders when extraction fails`;

export const CONFIDENCE_FALLBACK_THRESHOLD = 0.9;

const CONFIDENCE = {
  PRIMARY: 0.97,
  SECONDARY: 0.82,
  LAYOUT: 0.74,
  CONTEXTUAL: 0.62,
  GLOBAL: 0.45,
  SYNTHETIC: 0.25,
  NONE: 0,
} as const;

const REVIEW_THRESHOLD = 0.85;
const FIELD_REVIEW_MIN = 0.5;

function field(
  value: string | null,
  confidence: number,
  method: ExtractionMethod,
  autoGenerated = false,
): FieldExtraction {
  const trimmed = value?.trim() ?? "";
  if (!trimmed || (confidence < CONFIDENCE.GLOBAL && !autoGenerated)) {
    return { value: null, confidence: CONFIDENCE.NONE, method: "none", autoGenerated: false };
  }
  return { value: trimmed, confidence, method, autoGenerated };
}

function pickHigher(current: FieldExtraction, candidate: FieldExtraction): FieldExtraction {
  if (!candidate.value) return current;
  if (!current.value || candidate.confidence > current.confidence) return candidate;
  return current;
}

function tier1FromLayout(lines: OcrLine[]): Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> {
  const out: Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> = {};

  for (const line of lines) {
    const appMatch = line.text.match(/APPLICATION\s+NO\s*:?\s*(PD[L1]-[A-Z0-9]+)/i);
    if (appMatch?.[1]) {
      const app = normalizeApplicationNo(appMatch[1]);
      if (isValidReceiptApplicationNo(app)) {
        out.Application_No = field(app, CONFIDENCE.PRIMARY, "layout_proximity");
      }
    }

    const billMatch = line.text.match(/BILL\s+REFERENCE\s+NO\s*:?\s*([A-Z0-9]{6,8})/i);
    if (billMatch?.[1]) {
      const bill = applyBillRefOcrCorrections(billMatch[1]);
      if (isValidReceiptBillRef(bill)) {
        out.Bill_Reference = field(bill, CONFIDENCE.PRIMARY, "layout_proximity");
      }
    }

    const dateMatch = line.text.match(
      /DATE\s*:?\s*(\d{1,2}\s+(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+(?:\d{4}|20\d[!l|IL1]?))/i,
    );
    if (dateMatch?.[1]) {
      const formatted = parseLongDateMatch(dateMatch[1]);
      if (formatted && isValidReceiptDate(formatted)) {
        out.Date = field(formatted, CONFIDENCE.PRIMARY, "layout_proximity");
      }
    }

    const idMatch = line.text.match(/ID\s*No\s*:?\s*(\d[\d\s]{6,12})/i);
    if (idMatch?.[1]) {
      const idDigits = idMatch[1].replace(/\D/g, "");
      if (isValidReceiptIdNumber(idDigits)) {
        out.ID_No = field(idDigits, CONFIDENCE.PRIMARY, "layout_proximity");
      }
    }

    const nameMatch = line.text.match(/Name\s*:?\s*([A-Za-z][A-Za-z\s]{5,})/i);
    if (nameMatch?.[1]) {
      const name = refineReceiptName(nameMatch[1]);
      if (isValidReceiptName(name)) {
        out.Name = field(name, CONFIDENCE.PRIMARY, "layout_proximity");
      }
    }
  }

  const appRaw = valueRightOfLabel(lines, /^APPLICATION$/i);
  const app = normalizeApplicationNo(appRaw);
  if (isValidReceiptApplicationNo(app)) {
    out.Application_No = field(app, CONFIDENCE.PRIMARY, "layout_proximity");
  }

  const idRaw = valueRightOfLabel(lines, /^ID$/i);
  const idDigits = idRaw.replace(/\D/g, "");
  if (isValidReceiptIdNumber(idDigits)) {
    out.ID_No = field(idDigits, CONFIDENCE.PRIMARY, "layout_proximity");
  }

  const totalLine = lines.find((l) => /Total\s*KES/i.test(l.text));
  if (totalLine) {
    const amountMatch = totalLine.text.match(/(\d[\d,]*)/);
    if (amountMatch?.[1] && isValidReceiptTotalKes(amountMatch[1])) {
      out.Amount = field(String(parseAmountKes(amountMatch[1])), CONFIDENCE.PRIMARY, "layout_proximity");
      out.Currency = field("KES", CONFIDENCE.PRIMARY, "layout_proximity");
    }
  }

  return out;
}

/** Tier 2b: parse combined header value row (PDL-… | bill ref | date), including split OCR. */
function tier2HeaderValueRow(
  texts: string[],
): Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> {
  const out: Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> = {};
  for (const source of texts) {
    if (!source.trim()) continue;
    const row = parseHeaderValueRowFields(source);
    const ctx: BillRefContext = {
      applicationNo: row.applicationNo,
      idNumber: "",
      date: row.date,
    };
    if (row.applicationNo && isValidReceiptApplicationNo(row.applicationNo)) {
      out.Application_No = field(row.applicationNo, CONFIDENCE.SECONDARY, "secondary_keyword");
    }
    if (row.billReferenceNo && isValidReceiptBillRef(row.billReferenceNo, ctx)) {
      out.Bill_Reference = field(row.billReferenceNo, CONFIDENCE.SECONDARY, "secondary_keyword");
    }
    if (row.date && isValidReceiptDate(row.date)) {
      out.Date = field(row.date, CONFIDENCE.SECONDARY, "secondary_keyword");
    }
  }
  return out;
}

function tier2TextPass(
  text: string,
  options?: ParseReceiptOcrOptions,
): Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> {
  const row = extractRawReceiptFields(text, {
    headerText: options?.headerText,
    billRefText: options?.billRefText,
    applicationText: options?.applicationText,
    dateText: options?.dateText,
    headerValuesText: options?.headerValuesText,
    customerText: options?.customerText,
    idText: options?.idText,
  });
  const ctx: BillRefContext = {
    applicationNo: row.applicationNo,
    idNumber: row.idNumber,
    date: row.date,
  };
  const out: Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> = {};

  if (isValidReceiptName(row.name)) out.Name = field(row.name, CONFIDENCE.SECONDARY, "secondary_keyword");
  if (isValidReceiptDate(row.date)) out.Date = field(row.date, CONFIDENCE.SECONDARY, "secondary_keyword");
  if (isValidReceiptIdNumber(row.idNumber)) out.ID_No = field(row.idNumber, CONFIDENCE.SECONDARY, "secondary_keyword");
  if (isValidReceiptApplicationNo(row.applicationNo)) {
    out.Application_No = field(row.applicationNo, CONFIDENCE.SECONDARY, "secondary_keyword");
  }
  if (isValidReceiptBillRef(row.billReferenceNo, ctx)) {
    out.Bill_Reference = field(row.billReferenceNo, CONFIDENCE.SECONDARY, "secondary_keyword");
  }
  if (isValidReceiptTotalKes(row.totalKes)) {
    out.Amount = field(row.totalKes, CONFIDENCE.SECONDARY, "secondary_keyword");
    out.Currency = field("KES", CONFIDENCE.SECONDARY, "secondary_keyword");
  }

  return out;
}

function tier3Contextual(
  text: string,
  partial: ReceiptFormRow,
): Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> {
  const verified = verifyMissingReceiptFields(text, partial);
  const ctx: BillRefContext = {
    applicationNo: verified.applicationNo,
    idNumber: verified.idNumber,
    date: verified.date,
  };
  const out: Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> = {};

  if (!isValidReceiptIdNumber(partial.idNumber) && isValidReceiptIdNumber(verified.idNumber)) {
    out.ID_No = field(verified.idNumber, CONFIDENCE.CONTEXTUAL, "contextual");
  }
  if (!isValidReceiptName(partial.name) && isValidReceiptName(verified.name)) {
    out.Name = field(verified.name, CONFIDENCE.CONTEXTUAL, "contextual");
  }
  if (!isValidReceiptBillRef(partial.billReferenceNo, ctx) && isValidReceiptBillRef(verified.billReferenceNo, ctx)) {
    out.Bill_Reference = field(verified.billReferenceNo, CONFIDENCE.CONTEXTUAL, "contextual");
  }
  if (!isValidReceiptApplicationNo(partial.applicationNo) && isValidReceiptApplicationNo(verified.applicationNo)) {
    out.Application_No = field(verified.applicationNo, CONFIDENCE.CONTEXTUAL, "contextual");
  }
  if (!isValidReceiptDate(partial.date) && isValidReceiptDate(verified.date)) {
    out.Date = field(verified.date, CONFIDENCE.CONTEXTUAL, "contextual");
  }

  const deeperId = digDeeperReceiptIdNumber([text]);
  if (!isValidReceiptIdNumber(partial.idNumber) && deeperId) {
    out.ID_No = field(deeperId, CONFIDENCE.CONTEXTUAL, "contextual");
  }

  const deeperBill = digDeeperBillReferenceNo([text], ctx);
  if (!isValidReceiptBillRef(partial.billReferenceNo, ctx) && deeperBill) {
    out.Bill_Reference = field(deeperBill, CONFIDENCE.CONTEXTUAL, "contextual");
  }

  const deeperApp = digDeeperApplicationNo([text]);
  if (!isValidReceiptApplicationNo(partial.applicationNo) && deeperApp) {
    out.Application_No = field(deeperApp, CONFIDENCE.CONTEXTUAL, "contextual");
  }

  const deeperDate = digDeeperReceiptDate([text]);
  if (!isValidReceiptDate(partial.date) && deeperDate) {
    out.Date = field(deeperDate, CONFIDENCE.CONTEXTUAL, "contextual");
  }

  return out;
}

function tier4GlobalRegex(text: string): Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> {
  const out: Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> = {};
  const verified = verifyMissingReceiptFields(text, {
    name: "",
    idNumber: "",
    applicationNo: "",
    billReferenceNo: "",
    totalKes: "",
    date: "",
  });
  const ctx: BillRefContext = {
    applicationNo: verified.applicationNo,
    idNumber: verified.idNumber,
    date: verified.date,
  };

  if (isValidReceiptApplicationNo(verified.applicationNo)) {
    out.Application_No = field(verified.applicationNo, CONFIDENCE.GLOBAL, "global_regex");
  }
  if (isValidReceiptBillRef(verified.billReferenceNo, ctx)) {
    out.Bill_Reference = field(verified.billReferenceNo, CONFIDENCE.GLOBAL, "global_regex");
  }
  if (isValidReceiptIdNumber(verified.idNumber)) {
    out.ID_No = field(verified.idNumber, CONFIDENCE.GLOBAL, "global_regex");
  }
  if (isValidReceiptName(verified.name)) {
    out.Name = field(verified.name, CONFIDENCE.GLOBAL, "global_regex");
  }
  if (isValidReceiptDate(verified.date)) {
    out.Date = field(verified.date, CONFIDENCE.GLOBAL, "global_regex");
  }
  if (isValidReceiptTotalKes(verified.totalKes)) {
    out.Amount = field(verified.totalKes, CONFIDENCE.GLOBAL, "global_regex");
    out.Currency = field("KES", CONFIDENCE.GLOBAL, "global_regex");
  }

  return out;
}

function emptyFields(): ReceiptStructuredOutput {
  const none = field(null, CONFIDENCE.NONE, "none");
  return {
    Name: { ...none },
    Date: { ...none },
    ID_No: { ...none },
    Application_No: { ...none },
    Bill_Reference: { ...none },
    Amount: { ...none },
    Currency: { ...none },
    overallConfidence: 0,
    needsReview: true,
  };
}

function mergeFieldMaps(
  base: ReceiptStructuredOutput,
  patch: Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>>,
): ReceiptStructuredOutput {
  const keys = [
    "Name",
    "Date",
    "ID_No",
    "Application_No",
    "Bill_Reference",
    "Amount",
    "Currency",
  ] as const;
  const next = { ...base };
  for (const key of keys) {
    if (patch[key]) next[key] = pickHigher(next[key], patch[key]!);
  }
  return next;
}

function structuredToFormRow(s: ReceiptStructuredOutput): ReceiptFormRow {
  return finalizeReceiptFormRow({
    name: s.Name.value ?? "",
    date: s.Date.value ?? "",
    idNumber: s.ID_No.value ?? "",
    applicationNo: s.Application_No.value ?? "",
    billReferenceNo: s.Bill_Reference.value ?? "",
    totalKes: s.Amount.value ?? "",
  });
}

function scoreOverall(s: ReceiptStructuredOutput): number {
  const weights = [s.Name, s.Date, s.ID_No, s.Application_No, s.Bill_Reference, s.Amount];
  const filled = weights.filter((f) => f.value);
  if (!filled.length) return 0;
  return filled.reduce((sum, f) => sum + f.confidence, 0) / weights.length;
}

export type ExtractReceiptDocumentInput = {
  rawText: string;
  options?: ParseReceiptOcrOptions;
  layoutTokens?: OcrToken[];
};

/** Multi-tier receipt extraction with per-field confidence scores. */
export function extractReceiptDocument(input: ExtractReceiptDocumentInput): ReceiptStructuredOutput {
  const texts = [
    input.rawText,
    input.options?.headerText,
    input.options?.billRefText,
    input.options?.applicationText,
    input.options?.dateText,
    input.options?.headerValuesText,
    input.options?.customerText,
    input.options?.idText,
    ...(input.options?.extraTexts ?? []),
  ].filter((t): t is string => Boolean(t?.trim()));

  const combined = texts.join("\n");
  let structured = emptyFields();

  if (input.layoutTokens?.length) {
    const lines = groupTokensIntoLines(input.layoutTokens);
    structured = mergeFieldMaps(structured, tier1FromLayout(lines));
    const layoutText = linesToText(lines);
    structured = mergeFieldMaps(structured, tier2TextPass(layoutText, input.options));
  }

  const headerSources = [
    input.options?.headerText,
    input.options?.headerValuesText,
    input.options?.applicationText,
    input.options?.billRefText,
    input.options?.dateText,
  ].filter((t): t is string => Boolean(t?.trim()));
  structured = mergeFieldMaps(structured, tier2HeaderValueRow(headerSources));

  for (const source of texts) {
    structured = mergeFieldMaps(structured, tier2TextPass(source, input.options));
  }

  const partialRow = structuredToFormRow(structured);
  structured = mergeFieldMaps(structured, tier3Contextual(combined, partialRow));
  structured = mergeFieldMaps(structured, tier4GlobalRegex(combined));

  const legacyMerged = parseReceiptOcrText(combined, input.options);
  const legacyFields: Partial<Record<keyof ReceiptStructuredOutput, FieldExtraction>> = {};
  if (isValidReceiptName(legacyMerged.name)) {
    legacyFields.Name = field(legacyMerged.name, CONFIDENCE.SECONDARY, "secondary_keyword");
  }
  if (isValidReceiptIdNumber(legacyMerged.idNumber)) {
    legacyFields.ID_No = field(legacyMerged.idNumber, CONFIDENCE.SECONDARY, "secondary_keyword");
  }
  if (isValidReceiptApplicationNo(legacyMerged.applicationNo)) {
    legacyFields.Application_No = field(legacyMerged.applicationNo, CONFIDENCE.SECONDARY, "secondary_keyword");
  }
  const ctx: BillRefContext = {
    applicationNo: legacyMerged.applicationNo,
    idNumber: legacyMerged.idNumber,
    date: legacyMerged.date,
  };
  if (isValidReceiptBillRef(legacyMerged.billReferenceNo, ctx)) {
    legacyFields.Bill_Reference = field(legacyMerged.billReferenceNo, CONFIDENCE.SECONDARY, "secondary_keyword");
  }
  if (isValidReceiptDate(legacyMerged.date)) legacyFields.Date = field(legacyMerged.date, CONFIDENCE.SECONDARY, "secondary_keyword");
  if (isValidReceiptTotalKes(legacyMerged.totalKes)) {
    legacyFields.Amount = field(legacyMerged.totalKes, CONFIDENCE.SECONDARY, "secondary_keyword");
    legacyFields.Currency = field("KES", CONFIDENCE.SECONDARY, "secondary_keyword");
  }
  structured = mergeFieldMaps(structured, legacyFields);

  if (!structured.Currency.value && structured.Amount.value) {
    structured.Currency = field("KES", Math.min(structured.Amount.confidence, CONFIDENCE.SECONDARY), "contextual");
  }

  structured.overallConfidence = scoreOverall(structured);
  structured.needsReview =
    structured.overallConfidence < REVIEW_THRESHOLD ||
    [structured.Name, structured.ID_No, structured.Bill_Reference, structured.Amount].some(
      (f) => !f.value || f.confidence < FIELD_REVIEW_MIN,
    );

  return structured;
}

export function structuredOutputToJson(output: ReceiptStructuredOutput): Record<string, string | null> {
  const billRef = output.Bill_Reference.value;
  return {
    Name: output.Name.value,
    Date: output.Date.value,
    ID_No: output.ID_No.value,
    Application_No: output.Application_No.value,
    Bill_Reference_No: billRef,
    Bill_Reference: billRef,
    Amount: output.Amount.value,
    Currency: output.Currency.value ?? (output.Amount.value ? "KES" : null),
  };
}

export type ReceiptFieldJsonDetail = {
  value: string | null;
  confidence: number;
  method: ExtractionMethod;
  autoGenerated: boolean;
};

/** Full JSON with per-field confidence and auto-generation flags. */
export function structuredOutputToDetailedJson(output: ReceiptStructuredOutput): Record<
  string,
  string | null | number | boolean | ReceiptFieldJsonDetail
> {
  const flat = structuredOutputToJson(output);
  const detail = (f: FieldExtraction): ReceiptFieldJsonDetail => ({
    value: f.value,
    confidence: f.confidence,
    method: f.method,
    autoGenerated: f.autoGenerated ?? false,
  });
  return {
    ...flat,
    overallConfidence: output.overallConfidence,
    needsReview: output.needsReview,
    fields: {
      Name: detail(output.Name),
      Date: detail(output.Date),
      ID_No: detail(output.ID_No),
      Application_No: detail(output.Application_No),
      Bill_Reference_No: detail(output.Bill_Reference),
      Amount: detail(output.Amount),
      Currency: detail(output.Currency),
    },
  };
}

/** Mark fields that were filled by synthetic fallback on the final form row. */
export function applySyntheticFieldsToStructured(
  structured: ReceiptStructuredOutput,
  before: ReceiptFormRow,
  after: ReceiptFormRow,
): ReceiptStructuredOutput {
  const next = { ...structured };
  const markIfNew = (
    key: keyof Pick<
      ReceiptStructuredOutput,
      "Name" | "Date" | "ID_No" | "Application_No" | "Bill_Reference" | "Amount"
    >,
    wasValid: (v: string) => boolean,
    beforeVal: string,
    afterVal: string,
  ) => {
    if (!afterVal.trim() || wasValid(beforeVal)) return;
    if (!wasValid(afterVal)) return;
    next[key] = field(afterVal, CONFIDENCE.SYNTHETIC, "synthetic_fallback", true);
  };

  markIfNew("Name", isValidReceiptName, before.name, after.name);
  markIfNew("Date", isValidReceiptDate, before.date, after.date);
  markIfNew("ID_No", isValidReceiptIdNumber, before.idNumber, after.idNumber);
  markIfNew("Application_No", isValidReceiptApplicationNo, before.applicationNo, after.applicationNo);
  markIfNew(
    "Bill_Reference",
    (v) => isValidReceiptBillRef(v, { applicationNo: after.applicationNo, idNumber: after.idNumber }),
    before.billReferenceNo,
    after.billReferenceNo,
  );
  markIfNew("Amount", isValidReceiptTotalKes, before.totalKes, after.totalKes);

  if (next.Amount.autoGenerated && !next.Currency.value) {
    next.Currency = field("KES", CONFIDENCE.SYNTHETIC, "synthetic_fallback", true);
  }

  next.overallConfidence = scoreOverall(next);
  next.needsReview = true;
  return next;
}

export function applyStructuredToFormRow(output: ReceiptStructuredOutput): ReceiptFormRow {
  return structuredToFormRow(output);
}

export function mergeStructuredOutputs(outputs: ReceiptStructuredOutput[]): ReceiptStructuredOutput {
  let merged = emptyFields();
  for (const output of outputs) {
    merged = mergeFieldMaps(merged, {
      Name: output.Name,
      Date: output.Date,
      ID_No: output.ID_No,
      Application_No: output.Application_No,
      Bill_Reference: output.Bill_Reference,
      Amount: output.Amount,
      Currency: output.Currency,
    });
  }
  merged.overallConfidence = scoreOverall(merged);
  merged.needsReview =
    merged.overallConfidence < REVIEW_THRESHOLD ||
    [merged.Name, merged.ID_No, merged.Bill_Reference, merged.Amount].some(
      (f) => !f.value || f.confidence < FIELD_REVIEW_MIN,
    );
  return merged;
}

export function formRowsFromStructured(output: ReceiptStructuredOutput): ReceiptFormRow {
  return mergeReceiptFormRows([structuredToFormRow(output)]);
}
