import type {
  PhotoCategory,
  PhotoHeroSlide,
  PhotographySettings,
  ProcessStep,
  RateCardGroup,
  SitePhotoItem,
  SiteVideoItem,
  VideoCategory,
} from "./portfolioTypes";

export const UNCATEGORIZED_CATEGORY_ID = "cat-uncategorized";

export const DEFAULT_PHOTO_CATEGORIES: PhotoCategory[] = [
  { id: "cat-wedding", slug: "wedding", label: "Wedding", description: "Ceremony, reception, and couple portraits.", order: 0, visible: true },
  { id: "cat-traditional", slug: "traditional", label: "Traditional / Cultural", description: "Cultural ceremonies and heritage celebrations.", order: 1, visible: true },
  { id: "cat-engagement", slug: "engagement", label: "Engagement & Pre-wedding", order: 2, visible: true },
  { id: "cat-couples", slug: "couples", label: "Couples & Outdoor", order: 3, visible: true },
  { id: "cat-ladies", slug: "ladies", label: "Ladies", order: 4, visible: true },
  { id: "cat-gents", slug: "gents", label: "Gents", order: 5, visible: true },
  { id: "cat-kids", slug: "kids-family", label: "Kids & Family", order: 6, visible: true },
  { id: "cat-maternity", slug: "maternity", label: "Maternity & Newborn", order: 7, visible: true },
  { id: "cat-graduation", slug: "graduation", label: "Graduation", order: 8, visible: true },
  { id: "cat-corporate", slug: "corporate", label: "Corporate & Headshots", order: 9, visible: true },
  { id: "cat-studio", slug: "studio", label: "Studio", order: 10, visible: true },
  { id: "cat-bw", slug: "black-white", label: "Black & White", order: 11, visible: true },
  { id: "cat-fashion", slug: "fashion", label: "Fashion & Editorial", order: 12, visible: true },
  { id: "cat-events", slug: "events", label: "Events", description: "Birthdays, launches, and private events.", order: 13, visible: true },
  { id: "cat-product", slug: "product", label: "Product & Commercial", order: 14, visible: true },
  { id: "cat-lifestyle", slug: "lifestyle", label: "Lifestyle & Outdoor", order: 15, visible: true },
  { id: UNCATEGORIZED_CATEGORY_ID, slug: "uncategorized", label: "Gallery", order: 99, visible: false },
];

export const DEFAULT_VIDEO_CATEGORIES: VideoCategory[] = [
  { id: "vid-wedding", slug: "wedding-films", label: "Wedding films", order: 0, visible: true },
  { id: "vid-events", slug: "event-highlights", label: "Event highlights", order: 1, visible: true },
  { id: "vid-brand", slug: "brand-product", label: "Brand & product", order: 2, visible: true },
  { id: "vid-reels", slug: "reels", label: "Social reels", order: 3, visible: true },
  { id: "vid-corporate", slug: "corporate", label: "Corporate", order: 4, visible: true },
];

export const DEFAULT_PHOTOGRAPHY_SETTINGS: PhotographySettings = {
  whatsappNumber: "254759550133",
  whatsappBookingEnabled: true,
  rateCardsEnabled: true,
  bookingIntro: "Tell us what you need—we'll reply on WhatsApp with availability and next steps.",
  heroTitle: "Photography & Videography",
  heroSubtitle: "Bold frames, cinematic motion, and delivery built for brands, couples, and creators.",
  globalHeroAnimation: "filmDissolve",
  rateCardPageTitle: "Our Photography & Videography Packages",
  rateCardPageSubtitle: "",
  rateCardHeaderTagline: "Professional Photography & Videography Services",
  rateCardWhatsappNumbers: ["254759550133", "254726980150"],
};

export const DEFAULT_PHOTO_HERO_SLIDES: PhotoHeroSlide[] = [
  {
    id: "hero-1",
    src: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1920&q=85",
    srcLq: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=640&q=40",
    alt: "Wedding portrait",
    caption: "Weddings & celebrations",
    order: 0,
    animation: "kenburns",
  },
  {
    id: "hero-2",
    src: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=1920&q=85",
    srcLq: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=640&q=40",
    alt: "Studio portrait",
    caption: "Studio & portraits",
    order: 1,
    animation: "filmDissolve",
  },
  {
    id: "hero-3",
    src: "https://images.unsplash.com/photo-1511285560929-80b456fea0d2?w=1920&q=85",
    srcLq: "https://images.unsplash.com/photo-1511285560929-80b456fea0d2?w=640&q=40",
    alt: "Corporate headshot",
    caption: "Corporate & events",
    order: 2,
    animation: "slide",
  },
];

const DEFAULT_RATE_CARD_GROUPS_RAW = [
  {
    id: "rates-packages",
    label: "Packages",
    category: "wedding",
    sectionTitle: "Our Photography & Videography Packages",
    description: "",
    footnote: "",
    deliveryNote: "Delivery within 7 - 10 days",
    order: 0,
    packages: [
      {
        id: "pkg-golden",
        name: "Golden Package",
        price: "KSH 120,000",
        priceSuffix: "",
        detail: "",
        features: [
          "HD 1080 Professional Video 3 - 4 hrs @40,000",
          "High End Photos + 1 A2 and 1 A3 Mounts @25,000",
          "Media shared on Google Drive",
          "Drone Coverage @20,000",
          "Pre wedding Reels and Photos @25,000",
          "Transport @10,000",
        ],
        includes: [
          "2 Professional Videographers",
          "2 Professional Photographers",
          "High end Photos and Footages",
        ],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-silver",
        name: "Silver Package",
        price: "KSH 80,000",
        priceSuffix: "",
        detail: "",
        features: [
          "HD 1080 Professional Video 2 - 3 hrs @30,000",
          "High End Photos + 1 A2 mount @20,000",
          "Media shared on Google Drive",
          "Drone Coverage @20,000",
          "Transport @10,000",
        ],
        includes: [
          "2 Professional Videographers",
          "2 Professional Photographers",
          "High end Photos and Footages",
        ],
        deliveryNote: "",
        highlight: true,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-bronze",
        name: "Bronze Package",
        price: "KSH 55,000",
        priceSuffix: "",
        detail: "",
        features: [
          "HD 1080 Professional Video 2 - 3 hrs @30,000",
          "High End Photos @15,000",
          "Media shared on Google Drive",
          "Transport @10,000",
        ],
        includes: [
          "2 Professional Videographers",
          "1 Professional Photographer",
          "High end Photos and Footages",
        ],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-starter",
        name: "Starter Package",
        price: "KSH 40,000",
        priceSuffix: "",
        detail: "",
        features: [
          "HD 1080 Professional Video 1 - 2 hrs @25,000",
          "High End Photos @15,000",
          "Media shared on Google Drive",
          "Transport on Client",
        ],
        includes: [
          "2 Professional Videographers",
          "1 Professional Photographer",
          "High end Photos and Footages",
        ],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
    ],
  },
  {
    id: "rates-engagement",
    label: "Engagement",
    category: "other",
    sectionTitle: "Engagement packages",
    description: "Pre-wedding and engagement sessions with edited photos and highlight films.",
    footnote: "",
    deliveryNote: "Delivery within 7–10 days",
    order: 1,
    packages: [
      {
        id: "pkg-eng-starter",
        name: "Starter Package",
        price: "KSH 30,000",
        priceSuffix: "",
        detail: "",
        features: [
          "1 hour of coverage",
          "1 location",
          "20 high-resolution edited photos",
          "Short highlight video (~1 minute)",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-eng-classic",
        name: "Classic Package",
        price: "KSH 50,000",
        priceSuffix: "",
        detail: "",
        features: [
          "2 hours of coverage",
          "Up to 2 locations",
          "40 high-resolution edited photos",
          "Highlight video (2–3 minutes)",
          "Small photo album",
        ],
        includes: [],
        deliveryNote: "",
        highlight: true,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-eng-premium",
        name: "Premium Package",
        price: "KSH 80,000",
        priceSuffix: "",
        detail: "",
        features: [
          "Half-day session (up to 4 hours)",
          "Multiple outfit changes",
          "Up to 3 locations",
          "60+ high-resolution edited photos",
          "Cinematic highlight film (5 minutes)",
          "Custom photo album",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
    ],
  },
  {
    id: "rates-anniversary",
    label: "Anniversary",
    category: "other",
    sectionTitle: "Anniversary packages",
    description: "Celebrate your milestone with photos, films, and albums tailored to your story.",
    footnote: "",
    deliveryNote: "Delivery within 7–10 days",
    order: 2,
    packages: [
      {
        id: "pkg-ann-starter",
        name: "Starter Anniversary Package",
        price: "KSH 40,000",
        priceSuffix: "",
        detail: "",
        features: [
          "1-hour photo session",
          "1 location",
          "20 edited photos",
          "Simple digital gallery",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-ann-classic",
        name: "Classic Anniversary Package",
        price: "KSH 60,000",
        priceSuffix: "",
        detail: "",
        features: [
          "2-hour session",
          "Up to 2 locations",
          "Highlight video (2 minutes)",
          "40 edited photos",
          "Keepsake album",
        ],
        includes: [],
        deliveryNote: "",
        highlight: true,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-ann-premium",
        name: "Premium Anniversary Package",
        price: "KSH 90,000",
        priceSuffix: "",
        detail: "",
        features: [
          "Half-day shoot",
          "Multiple outfits",
          "Multiple locations",
          "Longer highlight film (3–5 minutes)",
          "Premium album",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
    ],
  },
  {
    id: "rates-birthdays",
    label: "Birthdays",
    category: "events",
    sectionTitle: "Birthday packages",
    description: "Accessible packages for kids’ parties, family milestones, and milestone birthdays.",
    footnote: "",
    deliveryNote: "Delivery within 7–10 days",
    order: 3,
    packages: [
      {
        id: "pkg-bday-kids",
        name: "Kids’ Celebration Package",
        price: "KSH 15,000",
        priceSuffix: "",
        detail: "",
        features: [
          "1 hour of coverage",
          "1 location",
          "15 edited photos",
          "Themed backdrop",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-bday-family",
        name: "Family Milestone Package",
        price: "KSH 25,000",
        priceSuffix: "",
        detail: "",
        features: [
          "2 hours of coverage",
          "Up to 2 locations",
          "25 edited photos",
          "Simple highlight slideshow",
        ],
        includes: [],
        deliveryNote: "",
        highlight: true,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-bday-milestone",
        name: "Milestone Birthday",
        price: "KSH 30,000",
        priceSuffix: "",
        detail: "",
        features: [
          "3 hours of coverage",
          "Up to 2 locations",
          "Highlight video",
          "30 edited photos",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-bday-platinum",
        name: "Platinum Package",
        price: "KSH 40,000",
        priceSuffix: "",
        detail: "",
        features: [
          "4 hours of coverage",
          "Full event coverage",
          "Multiple outfits",
          "Highlight film",
          "Custom album",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
    ],
  },
  {
    id: "rates-graduation",
    label: "Graduation",
    category: "events",
    sectionTitle: "Graduation packages",
    description:
      "Portraits, group shots, and full celebration coverage—from classic grad photos to cinematic reels and albums.",
    footnote: "",
    deliveryNote: "Delivery within 7–10 days",
    order: 4,
    packages: [
      {
        id: "pkg-grad-classic",
        name: "Classic Portrait Package",
        price: "KSH 25,000",
        priceSuffix: "",
        detail: "",
        features: [
          "Individual or small group portraits",
          "20 edited photos",
          "Ideal for grad portraits & quick sessions",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-grad-family",
        name: "Family & Friends Package",
        price: "KSH 40,000",
        priceSuffix: "",
        detail: "",
        features: [
          "Edited photos + short highlight reel",
          "Up to 2 locations",
          "Group shots with family & friends",
        ],
        includes: [],
        deliveryNote: "",
        highlight: true,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-grad-reel",
        name: "Reel & Event Package",
        price: "KSH 50,000",
        priceSuffix: "",
        detail: "",
        features: [
          "Full celebration captured as a highlight reel",
          "Event coverage focused on the grad day",
          "Photos from key moments",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-grad-premium",
        name: "Premium Graduation Experience",
        price: "KSH 70,000",
        priceSuffix: "",
        detail: "",
        features: [
          "Full event coverage",
          "Cinematic highlight reel",
          "Professional photo album",
          "Personal video montage",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
    ],
  },
  {
    id: "rates-funeral",
    label: "Funeral",
    category: "other",
    sectionTitle: "Funeral & memorial packages",
    description: "Respectful coverage for funerals, memorials, and family gatherings—with photos and films to honor your loved one.",
    footnote: "",
    deliveryNote: "Delivery within 7–10 days",
    order: 5,
    packages: [
      {
        id: "pkg-funeral-tribute",
        name: "Simple Tribute Package",
        price: "KSH 15,000",
        priceSuffix: "",
        detail: "",
        features: [
          "1 hour of coverage at the funeral or memorial",
          "Simple family portrait after the service",
          "10 edited photos",
          "All digital files provided",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-funeral-gathering",
        name: "Family Gathering Package",
        price: "KSH 25,000",
        priceSuffix: "",
        detail: "",
        features: [
          "2 hours of coverage",
          "Family-focused photo session",
          "Up to 3 locations",
          "20 edited photos",
          "Short highlight video (1–2 minutes)",
        ],
        includes: [],
        deliveryNote: "",
        highlight: true,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-funeral-memorial",
        name: "Memorial Event Package",
        price: "KSH 40,000",
        priceSuffix: "",
        detail: "",
        features: [
          "Full memorial service coverage",
          "3 hours of coverage",
          "Video tribute with interviews or messages",
          "30 edited photos",
          "All digital files + one highlight reel",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-funeral-premium",
        name: "Premium Memorial Experience",
        price: "KSH 60,000",
        priceSuffix: "",
        detail: "",
        features: [
          "Up to 4 hours of coverage",
          "Full event coverage",
          "Multiple outfit changes (if desired)",
          "Personalized video montage",
          "40 edited photos",
          "Premium photo album",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
    ],
  },
  {
    id: "rates-corporate",
    label: "Corporate",
    category: "corporate",
    sectionTitle: "Corporate packages",
    description: "Event coverage, brand films, and deliverables for launches, conferences, and company milestones.",
    footnote:
      "Add-ons (any package): Drone shot package from KSH 10,000 — aerial views of the venue or event. Branded slideshow (logo overlays, company info, pro editing) — KSH 10,000. Both are delivered with your final files. Invoices available for businesses.",
    deliveryNote: "",
    order: 6,
    packages: [
      {
        id: "pkg-corp-essentials",
        name: "Essentials Package",
        price: "KSH 30,000",
        priceSuffix: "",
        detail: "",
        features: [
          "4 hours of coverage (1 photographer + 1 videographer)",
          "Single-location shoot",
          "Up to 50 edited photos",
          "Highlight reel (2 minutes)",
          "All digital files — delivery within 1 week",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-corp-business",
        name: "Business-Class Package",
        price: "KSH 50,000",
        priceSuffix: "",
        detail: "",
        features: [
          "6 hours of coverage",
          "Up to 2 locations",
          "2 photographers",
          "80 edited photos",
          "Highlight video (3 minutes)",
          "Branded slideshow for presentations",
          "Delivery within 5 days",
        ],
        includes: [],
        deliveryNote: "",
        highlight: true,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-corp-executive",
        name: "Executive Package",
        price: "KSH 80,000",
        priceSuffix: "",
        detail: "",
        features: [
          "10 hours of coverage",
          "Up to 3 locations",
          "2 photographers + 1 videographer",
          "150 edited photos",
          "Cinematic highlight (5 minutes)",
          "Drone footage (if applicable)",
          "Custom video recap",
          "All files delivered within 7 days",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
    ],
  },
  {
    id: "rates-real-estate",
    label: "Real estate",
    category: "other",
    sectionTitle: "Real estate packages",
    description: "Listing photos, walkthrough films, drone, and virtual tours for homes and developments.",
    footnote: "",
    deliveryNote: "",
    order: 7,
    packages: [
      {
        id: "pkg-re-standard",
        name: "Standard Listing Package",
        price: "KSH 15,000",
        priceSuffix: "",
        detail: "",
        features: [
          "20–25 high-resolution photos",
          "1 location",
          "Interior and exterior shots",
          "Delivered in 3–5 days",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-re-enhanced",
        name: "Enhanced Listing Package",
        price: "KSH 25,000",
        priceSuffix: "",
        detail: "",
        features: [
          "25–30 edited photos",
          "Drone shots for exterior",
          "Short highlight video (60 seconds)",
          "Delivered in 5 days",
        ],
        includes: [],
        deliveryNote: "",
        highlight: true,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-re-premium",
        name: "Premium Package",
        price: "KSH 40,000",
        priceSuffix: "",
        detail: "",
        features: [
          "60+ photos",
          "Cinematic walkthrough video (2 minutes)",
          "Drone footage",
          "Virtual tour of the property",
          "Delivered in 7 days",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
      {
        id: "pkg-re-showcase",
        name: "Full Development Showcase",
        price: "KSH 70,000",
        priceSuffix: "",
        detail: "",
        features: [
          "10 hours of coverage",
          "Multiple locations",
          "Drone coverage",
          "Custom video",
          "Virtual tours",
          "Premium marketing slideshow",
          "All files delivered in 7 days",
        ],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book on WhatsApp",
      },
    ],
  },
  {
    id: "rates-portraits",
    label: "Portraits & studio",
    category: "portraits",
    sectionTitle: "Portrait & studio packages",
    description: "Individual, family, and professional portrait sessions.",
    footnote: "Studio sessions in Nairobi. Extra retouching available on request.",
    deliveryNote: "",
    order: 8,
    packages: [
      {
        id: "p7",
        name: "Individual",
        price: "KES 8,000",
        priceSuffix: "per session",
        detail: "",
        features: ["1 hour studio", "15 retouched images", "2 outfit changes", "Online delivery"],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book session",
      },
      {
        id: "p8",
        name: "Family / group",
        price: "KES 12,000",
        priceSuffix: "per session",
        detail: "",
        features: ["90 minutes", "25 images", "Group + individual shots", "Color grade"],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book session",
      },
      {
        id: "p9",
        name: "Headshots",
        price: "KES 6,500",
        priceSuffix: "per person",
        detail: "",
        features: ["LinkedIn-ready crops", "Same-day selects", "Light retouch", "15 min slots"],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book headshots",
      },
    ],
  },
  {
    id: "rates-video",
    label: "Videography",
    category: "videography",
    sectionTitle: "Videography packages",
    description: "Films, reels, and event highlights for web and social.",
    footnote: "Music licensing included on standard packages unless otherwise noted.",
    deliveryNote: "",
    order: 9,
    packages: [
      {
        id: "p10",
        name: "Highlight reel",
        price: "KES 25,000",
        priceSuffix: "per film",
        detail: "",
        features: ["2–3 minute edit", "Color grade", "Licensed music", "Social crops"],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Book film",
      },
      {
        id: "p11",
        name: "Full event film",
        price: "KES 55,000",
        priceSuffix: "per event",
        detail: "",
        features: ["Multi-camera", "Speeches included", "Cinematic edit", "Delivery in 14 days"],
        includes: [],
        deliveryNote: "",
        highlight: true,
        popularLabel: "Most Popular",
        ctaLabel: "Book film",
      },
      {
        id: "p12",
        name: "Brand film",
        price: "Custom",
        priceSuffix: "quote",
        detail: "",
        features: ["Script support", "B-roll day", "Motion graphics", "Multiple revisions"],
        includes: [],
        deliveryNote: "",
        highlight: false,
        popularLabel: "Most Popular",
        ctaLabel: "Request quote",
      },
    ],
  },
];

export const DEFAULT_RATE_CARD_GROUPS: RateCardGroup[] = DEFAULT_RATE_CARD_GROUPS_RAW.map((g) => ({
  ...g,
  visible: true,
  packages: g.packages.map((p) => ({ ...p, visible: true })),
}));

export const DEFAULT_PROCESS_STEPS: ProcessStep[] = [
  { step: "01", title: "Discovery", text: "Brief, mood board, shot list, and location scouting." },
  { step: "02", title: "Production", text: "On-set direction, lighting, and backup coverage." },
  { step: "03", title: "Post", text: "Color grade, retouch, and client proofing gallery." },
  { step: "04", title: "Delivery", text: "Cloud gallery, social crops, and archival masters." },
];

export const DEFAULT_VIDEO_GALLERY: SiteVideoItem[] = [
  {
    id: "v1",
    title: "Brand film — product launch",
    description: "Short-form brand story with motion graphics and on-location B-roll.",
    embedId: "ysz5S6PUM-U",
    categoryId: "vid-brand",
    featured: true,
    visible: true,
    order: 0,
  },
  {
    id: "v2",
    title: "Event highlight reel",
    description: "Fast-paced recap cut for social and website hero loops.",
    embedId: "ysz5S6PUM-U",
    categoryId: "vid-events",
    featured: false,
    visible: true,
    order: 1,
  },
];

export function buildDefaultPhotoGallery(): SitePhotoItem[] {
  const items: Omit<SitePhotoItem, "categoryId">[] = [
    { id: "1", src: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80", alt: "Wedding portrait", tall: true, featured: true, order: 0 },
    { id: "2", src: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80", alt: "Camera gear", tall: false, featured: false, order: 1 },
    { id: "3", src: "https://images.unsplash.com/photo-1478737270239-2fbf6bd88f7f?w=800&q=80", alt: "Live event", tall: false, featured: false, order: 2 },
    { id: "4", src: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&q=80", alt: "Studio portrait", tall: true, featured: true, order: 3 },
    { id: "5", src: "https://images.unsplash.com/photo-1511285560929-80b456fea0d2?w=800&q=80", alt: "Corporate headshot", tall: false, featured: false, order: 4 },
    { id: "6", src: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80", alt: "Outdoor couple", tall: true, featured: false, order: 5 },
  ];
  const categoryIds = ["cat-wedding", "cat-events", "cat-events", "cat-studio", "cat-corporate", "cat-couples"];
  return items.map((item, i) => ({ ...item, categoryId: categoryIds[i] ?? UNCATEGORIZED_CATEGORY_ID }));
}
